config/routes.rb
Mdvn::Application.routes.draw do |map|
  match 'about', :to => 'pages#about', :as => 'about'
  match 'help', :to => 'pages#help', :as => 'help'

  resources :bibliomes do
    resources :articles
    resources :journals
    resources :authors
    resources :subjects
    resources :genes
    resources :pubtypes

    collection do
      get :recent
      get :popular
      get :inprocess
      post :import
    end
  end

  root :to => "pages#home"

end

app/models/bibliome.rb
class Bibliome < ActiveRecord::Base
  has_many :bibliome_articles
  has_many :articles, :through => :bibliome_articles, :order => "#{BibliomeArticle.table_name}.pubdate desc"
  has_many :journals, :class_name => "BibliomeJournal", :include => :journal
  has_many :authors, :class_name => "BibliomeAuthor", :include => :author
  has_many :subjects, :class_name => "BibliomeSubject", :include => :subject
  #has_many :genes, :class_name => "BibliomeGene", :include => :gene
  has_many :pubtypes, :class_name => "BibliomePubtype", :include => :pubtype
  has_many :author_journals
  has_many :coauthorships
  has_many :author_subjects
  has_many :author_genes
  has_many :author_pubtypes
  has_many :journal_subjects
  has_many :journal_genes
  has_many :journal_pubtypes
  has_many :cosubjects
  has_many :subject_genes
  
  validates_uniqueness_of :name
  
  scope :built, where(:built => true)
  scope :recent, lambda {|limit|
    built.order("built_at desc").limit(limit)
  }
  scope :popular, lambda {|limit|
    built.order("hits desc").limit(limit)
  }
  scope :enqueued, where(:built => false, :articles_count => 0)
  scope :inprocess, :conditions => ["built = ? AND all_articles_count > 0", false]
  scope :last_built, built.order("built_at desc").limit(1)

  def status
    if built?
      "finished importing"
    else
      "imported"
    end
  end

  def hit!
    if built?
      self.delete_at = 2.weeks.from_now
      self.increment! :hits
    end
  end

  def processing_time
    to_time = built_at || Time.now
    from_time = started_at || Time.now
    (to_time - from_time).round
  end

  def build_speed
    (all_articles_count.to_f / processing_time.to_f * 60).round.to_s + " articles/min"
  end

  def start_year
    BibliomeArticle.minimum('pubdate', :conditions => ["bibliome_id = ?", id]).year
  end

  def end_year
    BibliomeArticle.maximum('pubdate', :conditions => ["bibliome_id = ?", id]).year
  end
end

app/controllers/bibliomes_controller.rb
class BibliomesController < ApplicationController
  def index
    @bibliomes = Bibliome.built.paginate(:page => params[:page], :per_page => 10)
    @prefix = "All "
  end

  def recent
    @bibliomes = Bibliome.recent.paginate(:page => params[:page], :per_page => 10)
    @prefix = "Recent "
  end

  def popular
    @bibliomes = Bibliome.popular.paginate(:page => params[:page], :per_page => 10)
    @prefix = "Popular "
  end

  def inprocess
    @bibliomes = Bibliome.inprocess.paginate(:page => params[:page], :per_page => 10)
    @prefix = "In Process "
  end

  def show
    @bibliome = Bibliome.find(params[:id])
    @bibliome.hit!
  end

  def new
    @q = params[:q]
    @count = 0
    unless @q.blank?
      @webenv, @count = Medvane::Eutils.esearch(@q)
      @bibliomes = Bibliome.find_all_by_query(@q)
      if @count > 0
        @medline = Medvane::Eutils.efetch(@webenv, 0, 5, "medline")
        @show_count = @count < 5 ? @count : 5
        @bibliome_name = Digest::MD5.hexdigest(Time.now.to_f.to_s + @q)
      end
    end
  end

  def import
    q = params[:q]
    webenv = params[:w]
    count = params[:c] || 0
    @bibliome = Bibliome.find_or_initialize_by_name(params[:name])
    if @bibliome.new_record? and q.blank? == false and webenv.blank? == false and count.to_i > 1
      @bibliome.query = q
      @bibliome.total_articles = count
      @bibliome.save!
      priority = (400 / Math.log(count)).to_i
      0.step(@bibliome.total_articles.to_i, PubmedImport::RETMAX) do |retstart| 
        Delayed::Job.enqueue(PubmedImport.new(@bibliome.id, webenv, retstart), priority)
        priority -= 1
      end
      redirect_to @bibliome
    else
      redirect_to new_bibliome_path
    end
  end

  def edit
    @bibliome = Bibliome.find(params[:id])
  end

  def create
    @bibliome = Bibliome.new(params[:bibliome])

    respond_to do |format|
      if @bibliome.save
        flash[:notice] = 'Bibliome was successfully created.'
        format.html { redirect_to(@bibliome) }
        format.xml  { render :xml => @bibliome, :status => :created, :location => @bibliome }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @bibliome.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @bibliome = Bibliome.find(params[:id])

    respond_to do |format|
      if @bibliome.update_attributes(params[:bibliome])
        flash[:notice] = 'Bibliome was successfully updated.'
        format.html { redirect_to(@bibliome) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @bibliome.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @bibliome = Bibliome.find(params[:id])
    @bibliome.destroy

    respond_to do |format|
      format.html { redirect_to(bibliomes_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/bibliomes_helper.rb
module BibliomesHelper
  def status(bibliome)
    unless bibliome.built?
      status = "#{number_with_delimiter(bibliome.total_articles)} articles are enqueued for importing. Please bookmark this page and come back later."
      progressbar = ''
      if bibliome.all_articles_count > 0
        percentage = sprintf("%d", bibliome.all_articles_count.to_f / bibliome.total_articles.to_f * 100)
        started_at = bibliome.started_at || Time.now
        rate = bibliome.all_articles_count.to_f / (Time.now - started_at)
        time_left = ((bibliome.total_articles - bibliome.all_articles_count).to_f / rate).to_i
        estimate = distance_of_time_in_words(Time.now, Time.now + time_left)
        status = "#{number_with_delimiter(bibliome.all_articles_count)} of #{number_with_delimiter(bibliome.total_articles)} articles (#{percentage}%) were imported in #{processing_time(bibliome)} (#{bibliome.build_speed}). Estimated time to finish importing is #{estimate}."
        progressbar = content_tag(:div, content_tag(:div, content_tag(:div, "#{percentage}%", :style => "padding-left: 0.5em"), :style => "background-color: #ccc; width: #{percentage}%; border-right: 1px solid #913"), :style => "border: 1px solid #913; margin-top: 0.5em")
      end
      content_tag(:div, status + progressbar, :id => "bibliome_status")
    end
  end
  
  def processing_time(bibliome)
    to_time = bibliome.built_at || Time.now
    from_time = bibliome.started_at || Time.now
    distance_of_time_in_words(from_time, to_time, true)
  end

  def age(bibliome)
    if bibliome.built?
      time_ago_in_words(bibliome.built_at) + " ago"
    else
      "in process"
    end
  end

  def summary(bibliome)
    if bibliome.built?
      li = []
      ["article", "journal", "author", "subject", "pubtype"].each do |obj|
        counter_field = "#{@period}_#{obj}s_count"
        count = bibliome.send(counter_field)
        link_text = pluralize(number_with_delimiter(count), obj.titleize)
        link_path = controller.send("bibliome_#{obj}s_path", bibliome, :period => @link_period)
        li.push(content_tag(:li, link_to(link_text, link_path)))
      end
      content_tag(:ul, li.join("\n").html_safe)
    end
  end
end

app/views/bibliomes/_form.html.erb
<%= form_for(@bibliome) do |f| %>
  <% if @bibliome.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@bibliome.errors.count, "error") %> prohibited this bibliome from being saved:</h2>
    <ul>
    <% @bibliome.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :query %><br />
    <%= f.text_area :query %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bibliomes/edit.html.erb
<h1>Editing bibliome</h1>

<% form_for(@bibliome) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<%= link_to 'Show', @bibliome %> |
<%= link_to 'Back', bibliomes_path %>

app/views/bibliomes/index.html.erb
<% page_title(@prefix + "Bibliomes") %>
<%= page_entries_info @bibliomes %>
<ul>
  <% for item in @bibliomes -%>
  <li><%= link_to(h(item.query), bibliome_path(item))%> <span class="age">(<%= number_with_delimiter(item.total_articles) %> articles, <%= age(item) %>)</span><%= status(item) %></li>
  <% end -%>
</ul>
<%= will_paginate @bibliomes %>

app/views/bibliomes/new.html.erb
<% page_title("Build Your Own Bibliome")%>
<% form_tag new_bibliome_path, :method => "get", :id => "pubmed_search" do %>
  <%= text_field_tag('q', @q, :id => "pubmed_search_q") %>
  <%= hidden_field_tag('count', @count, :name => nil) %>
  <%= submit_tag "Search PubMed", :name => nil, :disable_with => "Searching PubMed ...", :id => "pubmed_search_submit" %>
<% end -%>
  
<% if @count > 0 -%>
<% if @bibliomes.size > 0 -%>
  <ul>
    <% for item in @bibliomes -%>
    <li><%= link_to(h(item.query), bibliome_path(item))%> <span class="age">(<%= item.total_articles %> articles, <%= age(item) %>)</span></li>
    <% end -%>
  </ul>
<% end -%>
<div id="results_info">Results: <strong>1</strong> to <strong><%= @show_count %></strong> of <strong><%= number_with_delimiter(@count) %></strong> for <strong><%=h @q %></strong></div>
<ol id="results">
<% for m in @medline do -%>
  <li id="pmid_<%= m.pmid %>" class="citation"><div class="title"><%= m.title %></div><div class="authors"><%= m.pubmed['AU'].split(/\n/).join(", ")%></div><div class="source"><%= m.so %></div></li>
<% end -%>
</ol>

<% if @count > 1 -%>
<% form_tag import_bibliomes_path do %>
  <%= hidden_field_tag('name', @bibliome_name) %>
  <%= hidden_field_tag('q', @q) %>
  <%= hidden_field_tag('c', @count) %>
  <%= hidden_field_tag('w', @webenv) %>
  <%= submit_tag "Build your bibliome", :name => nil, :disable_with => "Building your bibliome ..." , :id => "build_bibliome_submit" %>
<% end -%>
<% else -%>
We need more than 1 article to build a bibliome. Let's try another search keyword!
<% end -%>
<% elsif @q.blank? == false -%>
<div id="results_info"><strong><%=h @q %></strong> was not found in PubMed.</div>
<% end -%>

app/views/bibliomes/show.html.erb
<% page_title(@bibliome.query)%>
<%= status(@bibliome) %>
<%= summary(@bibliome) %>

<% if @bibliome.built? -%>
<div class="age">Built <%= time_ago_in_words(@bibliome.built_at)%> ago, will be deleted in 2 weeks from now if there is no access.</div>
<% end -%>