config/routes.rb
Mdvn::Application.routes.draw do |map|
  match 'about', :to => 'pages#about', :as => 'about'
  match 'help', :to => 'pages#help', :as => 'help'

  resources :bibliomes do
    resources :articles
    resources :journals
    resources :authors
    resources :subjects
    resources :genes
    resources :pubtypes

    collection do
      get :recent
      get :popular
      get :inprocess
      post :import
    end
  end

  root :to => "pages#home"

end

app/models/journal.rb
class Journal < ActiveRecord::Base
  has_many :bibliome_journals, :order => "year"
  has_many :bibliomes, :through => :bibliome_journals
  has_many :articles
  has_many :author_journals
  has_many :authors, :through => :author_journals
  has_many :journal_subjects
  has_many :subjects, :through => :journal_subjects
  has_many :journal_genes
  has_many :genes, :through => :journal_genes
  has_many :journal_pubtypes
  has_many :pubtypes, :through => :journal_pubtypes
  
  validates_uniqueness_of :title, :scope => :abbr
  validates_uniqueness_of :abbr, :scope => :title
  
  def to_l
    abbr
  end
end

app/controllers/journals_controller.rb
class JournalsController < ApplicationController
  def index
    @journals = @bibliome.journals.period(@period).paginate(:page => params[:page], :per_page => 10, :total_entries => @bibliome.send("#{@period}_journals_count"))
  end

  def show
    @journal = Journal.find(params[:id])
    @authors = AuthorJournal.find(:all, :conditions => {:bibliome_id => @bibliome.id, :journal_id => @journal.id, :year => @period}, :order => "total desc", :limit => 10, :include => [:author, :bibliome])
    @subjects = JournalSubject.find(:all, :conditions => {:bibliome_id => @bibliome.id, :journal_id => @journal.id, :year => @period}, :order => "direct desc", :limit => 10, :include => [:subject, :bibliome])
    @pubtypes = JournalPubtype.find(:all, :conditions => {:bibliome_id => @bibliome.id, :journal_id => @journal.id, :year => @period}, :order => "total desc", :limit => 10, :include => [:pubtype, :bibliome])
  end
end

app/helpers/journals_helper.rb
module JournalsHelper
end

app/views/journals/index.html.erb
<% page_title("Journals", @bibliome.query)%>
<h2>Journals</h2>
<%= page_entries_info @journals %>
<ol>
<% @journals.each do |j| -%>
  <li><%= link_to(j.journal.abbr, bibliome_journal_path(@bibliome, j.journal, :period => @link_period)) %> <%= count(j.articles_count) %> <%= sparkline(@bibliome, j.journal)%></td>
<% end -%>
</ol>
<%= will_paginate @journals %>

app/views/journals/show.html.erb
<% page_title(@journal.abbr, "Journals", @bibliome.query)%>
<h2><%=h @journal.title %></h2>

<%= publication_history(@bibliome, @journal) %>
<%= top_neighbors(@authors, "author")%>
<%= top_neighbors(@subjects, "subject")%>
<%= top_neighbors(@pubtypes, "pubtype")%>