config/routes.rb
Mdvn::Application.routes.draw do |map|
  match 'about', :to => 'pages#about', :as => 'about'
  match 'help', :to => 'pages#help', :as => 'help'

  resources :bibliomes do
    resources :articles
    resources :journals
    resources :authors
    resources :subjects
    resources :genes
    resources :pubtypes

    collection do
      get :recent
      get :popular
      get :inprocess
      post :import
    end
  end

  root :to => "pages#home"

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :bibliome_articles
  has_many :bibliomes, :through => :bibliome_articles
  belongs_to :journal
  has_many :authorships
  has_many :authors, :through => :authorships
  has_many :topics
  has_many :subjects, :through => :topics
  has_many :article_types
  has_many :pubtypes, :through => :article_types
  has_many :published_genes
  has_many :genes, :through => :published_genes, :include => :taxonomy
  
  validates_associated :journal
end

app/models/article_type.rb
class ArticleType < ActiveRecord::Base
  belongs_to :article
  belongs_to :pubtype
end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :bibliome_authors, :order => "year"
  has_many :bibliomes, :through => :bibliome_authors
  has_many :authorships
  has_many :articles, :through => :authorships
  has_many :author_journals
  has_many :journals, :through => :author_journals
  has_many :coauthorship
  has_many :coauthors, :through => :coauthorship, :source => :coauthor_id
  has_many :author_subjects
  has_many :subjects, :through => :author_subjects
  has_many :author_genes
  has_many :genes, :through => :author_genes
  has_many :author_pubtypes
  has_many :pubtypes, :through => :author_pubtypes
  
  validates_uniqueness_of :fore_name, :scope => [:last_name, :suffix]
  
  def full_name
    ["#{last_name || ""}", "#{fore_name || ""}"].join(", ")
  end

  def init_name
    ["#{last_name || ""}", "#{initials || ""}"].join(" ")
  end

  def merge_with(author)
    
  end
  
  def to_l
    full_name
  end

  def see_also
    case initials.length
    when 1: Author.find(:all, :conditions => ["last_name = ? AND initials like ? AND id != ?", last_name, "#{initials.first}%", id])
    when 2: Author.find(:all, :conditions => ["last_name = ? AND (initials = ? OR initials =?) AND id != ?", last_name, initials.first, initials, id])
    else return
    end
  end
end

app/models/author_gene.rb
class AuthorGene < ActiveRecord::Base
  belongs_to :bibliome
  belongs_to :author
  belongs_to :gene
end

app/models/authorship.rb
class Authorship < ActiveRecord::Base
  belongs_to :article
  belongs_to :author
  
  validates_uniqueness_of :author_id, :scope => [:article_id, :position]
end

app/models/bibliome.rb
class Bibliome < ActiveRecord::Base
  has_many :bibliome_articles
  has_many :articles, :through => :bibliome_articles, :order => "#{BibliomeArticle.table_name}.pubdate desc"
  has_many :journals, :class_name => "BibliomeJournal", :include => :journal
  has_many :authors, :class_name => "BibliomeAuthor", :include => :author
  has_many :subjects, :class_name => "BibliomeSubject", :include => :subject
  #has_many :genes, :class_name => "BibliomeGene", :include => :gene
  has_many :pubtypes, :class_name => "BibliomePubtype", :include => :pubtype
  has_many :author_journals
  has_many :coauthorships
  has_many :author_subjects
  has_many :author_genes
  has_many :author_pubtypes
  has_many :journal_subjects
  has_many :journal_genes
  has_many :journal_pubtypes
  has_many :cosubjects
  has_many :subject_genes
  
  validates_uniqueness_of :name
  
  scope :built, where(:built => true)
  scope :recent, lambda {|limit|
    built.order("built_at desc").limit(limit)
  }
  scope :popular, lambda {|limit|
    built.order("hits desc").limit(limit)
  }
  scope :enqueued, where(:built => false, :articles_count => 0)
  scope :inprocess, :conditions => ["built = ? AND all_articles_count > 0", false]
  scope :last_built, built.order("built_at desc").limit(1)

  def status
    if built?
      "finished importing"
    else
      "imported"
    end
  end

  def hit!
    if built?
      self.delete_at = 2.weeks.from_now
      self.increment! :hits
    end
  end

  def processing_time
    to_time = built_at || Time.now
    from_time = started_at || Time.now
    (to_time - from_time).round
  end

  def build_speed
    (all_articles_count.to_f / processing_time.to_f * 60).round.to_s + " articles/min"
  end

  def start_year
    BibliomeArticle.minimum('pubdate', :conditions => ["bibliome_id = ?", id]).year
  end

  def end_year
    BibliomeArticle.maximum('pubdate', :conditions => ["bibliome_id = ?", id]).year
  end
end

app/models/bibliome_gene.rb
class BibliomeGene < ActiveRecord::Base
  belongs_to :bibliome
  belongs_to :genes
  
  validates_uniqueness_of :gene_id, :scope => [:bibliome_id, :year]

  scope :period, lambda {|range|
    where(:year => range).order("articles_count desc")
  }

  scope :bibliome, lambda {|bibliome|
    where(:bibliome_id => bibliome.id)
  }
end

app/models/coauthorship.rb
class Coauthorship < ActiveRecord::Base
  belongs_to :bibliome
  belongs_to :author
  belongs_to :coauthor, :class_name => "Author", :foreign_key => "coauthor_id"
end

app/models/gene.rb
class Gene < ActiveRecord::Base
  has_many :bibliome_genes, :order => "year"
  has_many :bibliomes, :through => :bibliome_genes
  belongs_to :taxonomy
  has_many :published_genes
  has_many :journal_genes
  has_many :author_genes
  has_many :subject_genes
end

app/models/graph.rb
class Graph < ActiveRecord::Base
  belongs_to :bibliome
  belongs_to :source, :polymorphic => true
  belongs_to :target, :polymorphic => true
end

app/models/journal.rb
class Journal < ActiveRecord::Base
  has_many :bibliome_journals, :order => "year"
  has_many :bibliomes, :through => :bibliome_journals
  has_many :articles
  has_many :author_journals
  has_many :authors, :through => :author_journals
  has_many :journal_subjects
  has_many :subjects, :through => :journal_subjects
  has_many :journal_genes
  has_many :genes, :through => :journal_genes
  has_many :journal_pubtypes
  has_many :pubtypes, :through => :journal_pubtypes
  
  validates_uniqueness_of :title, :scope => :abbr
  validates_uniqueness_of :abbr, :scope => :title
  
  def to_l
    abbr
  end
end

app/models/journal_gene.rb
class JournalGene < ActiveRecord::Base
  belongs_to :bibliome
  belongs_to :journal
  belongs_to :gene
end

app/models/mesh_tree.rb
class MeshTree < ActiveRecord::Base
  belongs_to :subject
end

app/models/pubtype.rb
class Pubtype < ActiveRecord::Base
  has_many :bibliome_pubtypes, :order => "year"
  has_many :bibliomes, :through => :bibliome_pubtypes
  has_many :article_types
  has_many :articles, :through => :article_types
  has_many :author_pubtypes
  has_many :authors, :through => :author_pubtypes
  has_many :journal_pubtypes
  has_many :journals, :through => :journal_pubtypes
  
  def to_l
    term
  end
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  has_many :bibliome_subjects, :order => "year"
  has_many :bibliomes, :through => :bibliome_subjects
  has_many :topics
  has_many :articles, :through => :topics
  has_many :mesh_trees
  has_many :mesh_ancestors
  has_many :ancestors, :through => :mesh_ancestors, :source => :ancestor
  has_many :author_subjects
  has_many :authors, :through => :author_subjects
  has_many :journal_subjects
  has_many :journals, :through => :journal_subjects
  has_many :subject_genes
  has_many :genes, :through => :subject_genes
  has_many :cosubjectships
  has_many :cosubjects, :through => :cosubjectships, :source => :cosubject_id
  
  def to_l
    term
  end
end

app/models/subject_gene.rb
class SubjectGene < ActiveRecord::Base
  belongs_to :bibliome
  belongs_to :subject
  belongs_to :gene
end

app/models/taxonomy.rb
class Taxonomy < ActiveRecord::Base
  has_many :genes
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :article
  belongs_to :subject
end

app/helpers/genes_helper.rb
module GenesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title><%= yield(:title) || controller.controller_name.titleize %> | Medvane </title>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<meta name="viewport" content="width=device-width">
<link rel="apple-touch-icon" href="/images/icon-57x57.png"/>
<%= csrf_meta_tag %>
<% if Rails.env == "production" %>
<link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/combo?2.8.0r4/build/reset-fonts-grids/reset-fonts-grids.css&2.8.0r4/build/base/base-min.css"/>
<% else -%>
<%= stylesheet_link_tag "yui-rfgb" %>
<% end -%>
<%= stylesheet_link_tag "screen" %>
<% if Rails.env == "production" %>
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', '<%= ENV['GOOGLE_ANALYTICS_UA']%>']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(ga);
  })();
</script>
<% end -%>
</head>
<body>
<div id="doc3" class="yui-t7">
<div id="hd" role="banner">
  <%= link_to(image_tag("medvane-137x30.png"), root_path) %>
  <ul id="toolbar">
    <li><%= link_to_unless_current("Home", root_path) %></li>
    <li><%= link_to_unless_current("About Us", about_path) %></li>
    <li><%= link_to_unless_current("Help", help_path) %></li>
  </ul><!-- #toolbar -->
</div><!-- #hd -->
<div id="bd" role="main">
<div class="yui-g">
<%= page_header(@bibliome) %>
<%= period_tab(@period) if @bibliome and @bibliome.built? %>
<%= yield %>
</div><!-- .yui-g -->
</div><!-- #bd -->
<div id="ft" role="contentinfo">
</div><!-- #ft -->
</div><!-- #doc4 .yui-t7 -->
</body>
</html>

app/views/pages/about.html.erb
<% page_title("About Us") -%>
<h2>Background</h2>
<p>Although, on average, more than 2,000 articles are added to <a href="http://pubmed.gov">MEDLINE/PubMed</a> daily and the total number of articles indexed is approaching 20 million, what the user views when searching PubMed is generally only a small number of retrieved articles. It is impossible to see the 'whole picture' or to see research trends. Most people rely on review articles for these purposes. Review articles are essentially an analysis of, at most, hundreds of articles that are manually selected by a domain expert.</p>

<h2>Processing Method</h2>
<p>To address these issues, we developed a fully automated system that analyzes MEDLINE data; builds a variety of interesting interrelationships among entities; and displays salient research trends over time. We have shown that our approach closely mirrors the information that is found in manually created review articles (<a href="#ref1">1</a>, <a href="#ref2">2</a>). Originally, Medvane was available either as a predefined bibliome (e.g., the MEDLINE subset of all the publications by Harvard authors, or the subset of all publications about a specific topic, such as autism), or by request from developers who would use our scripts to download and analyse a given bibliome and serve the results through a web interface. This limited the number of people who could effectively use Medvane for their own purposes. To make Medvane accessible to anyone, we recently integrated all the necessary processes into a single web application that allows users to specify their own subsets of MEDLINE data. This has resulted in this free public website.</p>

<h2>Server Run Time & Number of Users</h2>
<p>Our first public release of Medvane was the Harvard-specific Medvane (<a href="http://harvard.medvane.org">http://harvard.medvane.org</a>). This has been running for <%= time_ago_in_words(Date.new(2008, 8, 2)) %>, since August 2, 2008, and has served over 480,000 page views for about 90,000 unique visitors from 177 countries. It shows descriptive and quantitative history as well as recent trends of the biomedical research conducted by Harvard researchers over the past 40 years, published in some 220,000 articles.</p>

<h2>Input Data</h2>
<p>Users can now construct their personal bibliome through my.medvane.org in any arbitrary way by entering PubMed search query terms such as a single disease, multiple diseases, drugs, or a researcher name. Users can also upload lists of PubMed IDs if the article subset cannot be easily created by search keywords. This might be the case, for example, for all the articles from a specific institution or a specific country.</p>

<h2>Output</h2>
<p>The temporal network of metadata entities such as journal, author, subject, genes, etc. is represented in fully hyperlinked pages with graphical visualization.</p>

<h2>References</h2>

<ol>
  <li><a name="ref1"></a>McCray,A.T., Lee,K. (2008) Exploring semantic locality patterns in the biomedical literature. Proceedings of the Intelligent Data Analysis in bioMedicine and Pharmacology (IDAMAP) 2008.</li>
  <li><a name="ref2"></a>McCray,A.T., Lee,K. (2010) Ontological Change as a Reflection of Progress in a Scientific Discipline. Lect. Notes Comput. Sci., in press.</li>
</ol>

app/views/pages/help.html.erb
<% page_title("Help") -%>
<h2>Frequently Asked Questions</h2>

<ul>
  <li><a href="http://www.ncbi.nlm.nih.gov/bookshelf/br.fcgi?book=helppubmed&part=pubmedhelp" target="_blank">PubMed Help (NCBI)</a></li>
</ul>

app/views/pages/home.html.erb
<% page_title("Biomedical Research at a Glance") -%>

<h2>Build Your Own Bibliome</h2>

<%= form_tag new_bibliome_path, :method => "get", :id => "pubmed_search" do %>
  <%= text_field_tag('q', @q, :id => "pubmed_search_q") %>
  <%= hidden_field_tag('count', @count, :name => nil) %>
  <%= submit_tag "Search PubMed", :name => nil, :disable_with => "Searching PubMed ...", :id => "pubmed_search_submit" %>
  <div id="sample_search">
    Try these queries: 
    <%= link_to("Rett Syndrome", new_bibliome_path(:q => "Rett Syndrome"))%>
    <%= link_to("plos med[jour]", new_bibliome_path(:q => "plos med[jour]"))%>
  </div><!-- #sample_search -->
<% end %>

<% if !@recent.blank? %>
<h2>Recent Bibliomes</h2>
<ul>
  <% for item in @recent %>
  <li><%= link_to(h(item.query), bibliome_path(item))%> <span class="age">(<%= number_with_delimiter(item.total_articles) %> articles, <%= age(item) %>)</span></li>
  <% end %>
</ul>
<%= link_to("See more recent bibliomes", recent_bibliomes_path) if (Bibliome.count > 5) %>
<% end %>

<% if !@popular.blank? %>
<h2>Popular Bibliomes</h2>
<ul>
  <% for item in @popular %>
  <li><%= link_to(h(item.query), bibliome_path(item))%> <span class="age">(<%= number_with_delimiter(item.total_articles) %> articles, <%= age(item) %>)</span></li>
  <% end %>
</ul>
<%= link_to("See more popular bibliomes", popular_bibliomes_path) if (Bibliome.count > 5) %>
<% end %>